### ISSUE TITLE
已解决：不能配置 Permalinks

### ISSUE THREAD

**Issue by CyrusYip** [olOwOlo/hugo-theme-even#314]
在 `config.toml` 加上下面的代码之后 Hugo 就启动不了了：

```
[permalinks]
  post = "/post/:year/:month/:day/:slug/"
```

```bash
hugo server -D

panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/gohugoio/hugo/resources/page.PermalinkExpander.validate(0xc000a122a0, 0x0, 0xc0009e7d40, 0x0, 0x0, 0x9)
        github.com/gohugoio/hugo/resources/page/permalinks.go:178 +0x291
github.com/gohugoio/hugo/resources/page.PermalinkExpander.parse(0xc000a122a0, 0x0, 0xc0009e7d40, 0xc000a122d0, 0xc000529028, 0x0, 0xc0009fb820)
        github.com/gohugoio/hugo/resources/page/permalinks.go:118 +0x34c
github.com/gohugoio/hugo/resources/page.NewPermalinkExpander(0xc0009e7d40, 0xc00052cfa8, 0x4b, 0x1e8dba9, 0x3, 0x1e94d84)
        github.com/gohugoio/hugo/resources/page/permalinks.go:86 +0x768
github.com/gohugoio/hugo/resources.NewSpec(0xc0009e7d40, 0xc0009e7d70, 0x24662a0, 0xc00052cf58, 0xc0009e6a80, 0x24662c0, 0xc000010850, 0xc0001b7800, 0x9, 0x9, ...)
        github.com/gohugoio/hugo/resources/resource_spec.go:73 +0x13e
github.com/gohugoio/hugo/deps.New(0xc0009e6a80, 0xc0004bc100, 0xc00007fef0, 0x0, 0x0, 0x24a5400, 0xc00013d680, 0xc0009f5000, 0x1a, 0x27, ...)
        github.com/gohugoio/hugo/deps/deps.go:243 +0x2a9
github.com/gohugoio/hugo/hugolib.applyDeps(0xc0009e6a80, 0xc0004bc100, 0xc00007fef0, 0x0, 0x0, 0x24a5400, 0xc00013d680, 0xc0009f5000, 0x1a, 0x27, ...)
        github.com/gohugoio/hugo/hugolib/hugo_sites.go:468 +0x2e0
github.com/gohugoio/hugo/hugolib.newHugoSites(0xc0009e6a80, 0xc0004bc100, 0x0, 0x0, 0x0, 0x24a5400, 0xc00013d680, 0x0, 0x0, 0x0, ...)
        github.com/gohugoio/hugo/hugolib/hugo_sites.go:364 +0x5d8
github.com/gohugoio/hugo/hugolib.NewHugoSites(0xc0009e6a80, 0xc0004bc100, 0x0, 0x0, 0x0, 0x24a5400, 0xc00013d680, 0x0, 0x0, 0x0, ...)
        github.com/gohugoio/hugo/hugolib/hugo_sites.go:504 +0x122
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
        github.com/gohugoio/hugo/commands/commandeer.go:402 +0x264
sync.(*Once).doSlow(0xc0004b9240, 0xc000847988)
        sync/once.go:66 +0xec
sync.(*Once).Do(...)
        sync/once.go:57
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0009bc8f0, 0xc0009b0101, 0x24691c0, 0xc0004b6280)
        github.com/gohugoio/hugo/commands/commandeer.go:361 +0x888
github.com/gohugoio/hugo/commands.newCommandeer(0x101, 0xc0004489c0, 0x2466260, 0xc00051b400, 0xc00051ce40, 0x0, 0x0, 0x0, 0x1cdc1c0, 0xc0009c8e00, ...)
        github.com/gohugoio/hugo/commands/commandeer.go:185 +0x241
github.com/gohugoio/hugo/commands.initializeConfig(0x101, 0xc0004489c0, 0x2466260, 0xc00051b400, 0xc00051ce40, 0x0, 0x0, 0xc0002e2f20)
        github.com/gohugoio/hugo/commands/hugo.go:124 +0x76
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc00051b400, 0xc0006a0580, 0xc0004b6150, 0x0, 0x1, 0x0, 0x0)
        github.com/gohugoio/hugo/commands/server.go:238 +0x1d5
github.com/spf13/cobra.(*Command).execute(0xc0006a0580, 0xc0004b6130, 0x1, 0x1, 0xc0006a0580, 0xc0004b6130)
        github.com/spf13/cobra/command.go:838 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003f7b80, 0xc000519fb0, 0x8, 0xc00027df00)
        github.com/spf13/cobra/command.go:943 +0x317
github.com/gohugoio/hugo/commands.Execute(0xc000116070, 0x2, 0x2, 0x40939f, 0xc000100058, 0x0, 0x0)
        github.com/gohugoio/hugo/commands/hugo.go:90 +0xb9
main.main()
        github.com/gohugoio/hugo/main.go:23 +0x6c
```

请问 Even 主题如何配置 Permalinks 呢？

**Comment by CyrusYip** [comment]
发现解决方法了，`permalinks` 配置应该放在 `copyright = ""` 这一行的后面才行。

```
baseURL = "http://localhost:1313/"
languageCode = "en"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "Even - A super concise theme for Hugo"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-theme-even"
enableGitInfo = false # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 5                                              # 首页每页显示的文章数
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

[permalinks]
  post = "/post/:year/:month/:day/:slug/"
```
